### ISSUE TITLE
PS4 players don't get sent the menu

### ISSUE THREAD

**Issue by Unickorn** [Muqsit/InvMenu#73] opened 2020-06-01 21:38 UTC
People using ps4 to connect to servers have been reporting that the inventory doesn't pop up to them at all.

https://github.com/DaPigGuy/PiggyAuctions/issues/11
https://github.com/DaPigGuy/PiggyCrates/issues/65

I'm also having the same issue. Is this a client bug or is there anything InvMenu can fix?

Edit: master branch, used on piggyauctions

**Comment by TwistedAsylumMC** [comment] 2020-06-09 19:18
Can confirm this happens with any controller

**Comment by Muqsit** [comment] 2020-06-09 19:54
I am kind of lazy to setup my PS4 currently. I think what's causing this bug is the minimalism in specifying tile properties in NBT.

InvMenu sends nothing more than the `Tile::TAG_ID` and custom name of the container in the tile NBT (and pairx, pairz for double chests). PMMP specifies the `Tile::TAG_X`, `Tile::TAG_Y` and `Tile::TAG_Z` as well which is probably why physically chests open whereas InvMenu menus don't.
https://github.com/Muqsit/InvMenu/blob/master/src/muqsit/invmenu/metadata/SingleBlockMenuMetadata.php#L87-#L94

**Comment by AndreasHGK** [comment] 2020-06-22 12:34
I can confirm that the same issue occurs on my server

**Comment by Joshiiiii** [comment] 2020-07-27 12:35
The link is not active anymore. But the issue still appears. Anyone got a solution?

**Comment by Joshiiiii** [comment] 2020-08-15 13:09
Ps4 hasn't implemented servers yet, so it doesn't need a ping. So you have to remove the hack in https://github.com/Muqsit/InvMenu/blob/master/src/muqsit/invmenu/session/PlayerNetwork.php#L59-L64

**Comment by Muqsit** [comment] 2020-08-15 13:43
> Ps4 hasn't implemented servers yet, so it doesn't need a ping. So you have to remove the hack in https://github.com/Muqsit/InvMenu/blob/master/src/muqsit/invmenu/session/PlayerNetwork.php#L59-L64

By that argument, isn't this issue unnecessary to fix? PS4 hasn't implemented servers yet, so any hackarounds to access third party servers via PS4 are unstable.

**Comment by Joshiiiii** [comment] 2020-08-15 16:28
Oh, sorry for the wrong solution. Thanks for letting me know :)

**Comment by Muqsit** [comment] 2020-08-16 08:33
I'll have to close this issue. This isn't really a bug with InvMenu but an inconsistency found within the PS4 client. The PS4 client sends a different response in the NetworkStackLatencyPacket compared to other clients.
Besides, joining 3P servers via PS4 isn't officially supported anyway and any software or workaround doing so should also account for such inconsistencies — _Instead of cleaning the dirty waters

**Comment by Muqsit** [comment] 2020-08-16 08:34
I'll have to close this issue. This isn't really a bug with InvMenu but an inconsistency found within the PS4 client. The PS4 client sends a different response in the NetworkStackLatencyPacket compared to other clients.
Besides, joining 3P servers via PS4 isn't officially supported anyway and any software or workaround doing so should also account for such inconsistencies — _Instead of mopping the hazardous water every day, fix the pipes instead._

**Comment by xxAROX** [comment] 2020-08-29 14:34
I found a method, its very unstable but it works:
PlayerNetwork.php
```php
	public function notify(int $timestamp) : void{
		if ($this->session instanceof MyCustomPlayer) {
			if ($this->session->getOS() /*returns the device-os, you can find them at 'LoginPacket::$clientData["DeviceOS"]'*/ == 11) {
				if ($this->current !== null && $timestamp !== $this->current->timestamp) {
					$this->processCurrent(true);
				}
			} else {
				if ($this->current !== null && $timestamp === $this->current->timestamp) {
					$this->processCurrent(true);
				}
			}
		}
	}
```

**Comment by Muqsit** [comment] 2020-09-05 13:46
As much as I don't want to fix the network side of MCPE in a virion, this one is a special case as at the moment, pocketmine plugins and virions have to handle NetworkStackLatencyPacket on their own.

**Comment by Muqsit** [comment] 2020-09-23 13:00
Didn't mean to close, this change needs testing but I can't test at the moment due to a known crash on PS4 during xbox sign in.

**Comment by xxAROX** [comment] 2020-09-23 14:05
Here are some Discord-Tags:(PS4 users)
> SxnDxrkh#2995
> KimEd2r#2154
DM them, if you need testers.

**Comment by Muqsit** [comment] 2020-09-23 17:23
> Here are some Discord-Tags:(PS4 users)
> 
> > SxnDxrkh#2995
> > KimEd2r#2154
> > DM them, if you need testers.
@xxAROX reproducing this issue does not require multiple clients to coordinate with one another

**Closed** 2020-10-05 05:05 UTC
Labels: bug, client-sided bug

**Comment by Driesboy** [comment] 2020-10-05 17:33
I got reports it still doesn't work on PS4

**Comment by Muqsit** [comment] 2020-10-08 04:23
> I got reports it still doesn't work on PS4

@Driesboy I've tested it and works fine on PS4. The issue was due to incorrect timestamp values being sent by playstation client in response to NetworkStackLatencyPacket. All I can think of that could still cause this issue is:
- User is using an old client, `DeviceOS::PLAYSTATION` (or orbis) used to be `10` IIRC, it's now `11`
- User is actually experiencing #74
