### ISSUE TITLE
Unable to execute the inventory

### ISSUE THREAD

**Issue by 94832747228** [Muqsit/InvMenu#164] opened 2022-02-11 05:21 UTC
I removed the invmenu virion from my plugin and pput it in virions folder, when i click the chest, it send this:
Error: "Class 'VirakMC\MyCrate\libs\muqsit\invmenu\InvMenu' not found" (EXCEPTION) in "plugins/MyCrate (6)/src/VirakMC/MyCrate/MenuManager" at line 34
[12:20:17] [Server thread/CRITICAL]: #0 plugins/MyCrate (6)/src/VirakMC/MyCrate/EventListener(117): VirakMC\MyCrate\MenuManager->previewCrate(array[0], object pocketmine\Player)
[12:20:17] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): VirakMC\MyCrate\EventListener->onInteract(object pocketmine\event\player\PlayerInteractEvent)
[12:20:18] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object VirakMC\MyCrate\EventListener, object pocketmine\event\player\PlayerInteractEvent)
[12:20:18] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent)
[12:20:18] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/level/Level(1872): pocketmine\event\Event->call()
[12:20:18] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Player(2556): pocketmine\level\Level->useItemOn(object pocketmine\math\Vector3, object pocketmine\item\ItemBlock, integer 2, object pocketmine\math\Vector3, object pocketmine\Player, boolean 1)
[12:20:18] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(149): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[12:20:18] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(106): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[12:20:18] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[12:20:18] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
[12:20:18] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
[12:20:18] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Player(3323): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[12:20:18] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
[12:20:18] [Server thread/CRITICAL]: #13 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[15] 127.0.0.1 59093, object raklib\protocol\EncapsulatedPacket, integer 0)
[12:20:18] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
[12:20:18] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
[12:20:18] [Server thread/CRITICAL]: #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
[12:20:18] [Server thread/CRITICAL]: #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
[12:20:18] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1644556818.0322)
[12:20:18] [Server thread/CRITICAL]: #19 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
[12:20:18] [Server thread/CRITICAL]: #20 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
[12:20:18] [Server thread/CRITICAL]: #21 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[34] C:\Users\thanh\Desktop\PocketMine\, string[42] C:\Users\thanh\Desktop\PocketMine\plugins\)
[12:20:18] [Server thread/CRITICAL]: #22 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
[12:20:18] [Server thread/CRITICAL]: #23 pmsrc(11): require(string[89] phar://C:/Users/thanh/Desktop/PocketMine/PocketMine-MP.phar/src/pocketmine/Pocke)

**Comment by 94832747228** [comment] 2022-02-11 05:24
public function previewCrate(array $items, Player $player) {
        $menu = InvMenu::create(InvMenu::TYPE_DOUBLE_CHEST);
        $menu->getInventory()->setContents($items);
        $menu->setListener(InvMenu::readonly(function (DeterministicInvMenuTransaction $transaction) : void {}));
        $menu->setName("Crate");
        $menu->send($player);
    }

**Comment by Muqsit** [comment] 2022-02-11 05:52
Duplicate of #163. Your backtrace shouldn't be displaying traces of InvMenu in `libs\` folder in a plugin's source (see https://github.com/Muqsit/InvMenu/issues/163#issuecomment-1035682128).

**Closed as completed by Muqsit** 2022-02-11 05:52 UTC

**Comment by 94832747228** [comment] 2022-02-11 07:57
Musqit, is that mean I shoudln't put the inv menu in libs?

**Comment by 94832747228** [comment] 2022-02-11 08:22
[MyCrate (6).zip](https://github.com/Muqsit/InvMenu/files/8047055/MyCrate.6.zip)

   Please give me a specific reason and a good soloution
