### ISSUE TITLE
Minecraft game crashes

### ISSUE THREAD

**Issue by Eren5960** [Muqsit/InvMenu#97] opened 2020-08-09 11:12 UTC
I don't know why but in some cases minecraft game crashes. It has been tested on multiple devices. I think it's a situation with inventory closure.

Below is a sample code:

```php
$menu->setListener(function(InvMenuTransaction $ts) use ($menu, $map): InvMenuTransactionResult{
	$player = $ts->getPlayer();
	$in = $ts->getItemClicked();

	if($in->getId() === ItemIds::IRON_BARS) return $ts->discard(); // no listen iron bars
	$player->removeCurrentWindow();

	if(!SkyUtils::validate($player)) return $ts->discard(); // Application if not on SkyBlock island

	if($in->getId() === ItemIds::WOOL){ // back to form or close
		if($in->getMeta() === $map->toId(DyeColor::YELLOW())){ // back to form
			$player->sendForm(new EconomyForm($player));
		} // else close 
	}elseif($player->getCoins() >= ($price = self::getPrice($in->getName()))){ // coin control
		if($player->getInventory()->canAddItem($in)){
			$player->reduceCoins($price);
			$player->sendMessage($player->translate('forms.economy.coinShop.buy.success', [$in->getCustomName() . TextFormat::RESET]));
			return $ts->continue();
		}else{
	               $player->sendMessage($player->translate('error.generic.fullInventory'));
		}
	}else{
		$player->sendMessage($player->translate('error.generic.noCoins'));
	}
	return $ts->discard();
});
```

**Comment by Eren5960** [comment] 2020-08-09 11:13
No errors in the PocketMine console

**Comment by Muqsit** [comment] 2020-08-09 11:41
Duplicate of #84, download the api-4.0 branch of InvCrashFix for pmmp api4

**Closed by Muqsit** 2020-08-09 11:41 UTC
Labels: duplicate
