### ISSUE TITLE
Opening Windows

### ISSUE THREAD

**Issue by PixelzChris** [Muqsit/InvMenu#42] opened 2019-03-02 21:45 UTC
If I use more than 1 window and add items with transaction event to open other windows it doesnt work its glitching
-the hotbar disappears
-black screen...
But I can still use everything in the window which does matter because the game has glitched...

Ive changed the task delay so I can avoid such bugs...
Same Bug... why?
https://youtu.be/fD2nUk4PrlA
This is the plugin...

I have to update it to V1.0 . I have finished my work and the plugin is read but it has this bug......
Any help

(Also hopper is really buggy)

**Comment by Muqsit** [comment] 2019-03-03 03:48
I really cant do anything if there's no code provided. Please send the part of code which is liable for this issue.

**Comment by PixelzChris** [comment] 2019-03-03 08:07
So in my transaction event I have added this
```}elseif($item->getName() == C::WHITE . C::BOLD . "Go back\n" . C::RESET . C::GRAY . "Go back to settings menu.\n\n" . C::YELLOW . "Click here!"){
		        $player->removeAllWindows();
		        settings::openSettings($player);
		        $event->setCancelled();```
But every time I m using this and my hot bar inventory disappears...
But the transaction event works I can use every chests items etc.
But the problem is with the hot bar

**Comment by Muqsit** [comment] 2019-04-12 07:25
@PixelzChris this is related to #41. The game requires a delay between closing and opening a new inventory.
Closing this as duplicate of #41

**Closed by Muqsit** 2019-04-12 07:25 UTC
Labels: duplicate, vague
