### ISSUE TITLE
New verion for Invmenu for fix 

### ISSUE THREAD

**Issue by Ender-nguyen734** [Muqsit/InvMenu#195] opened 2022-12-06 06:44 UTC
When I update my server to 1.19.50 my server has crash with all plugin using invmenu
I hope you will to update invmenu for fix I love you :3

**Comment by Muqsit** [comment] 2022-12-06 07:23
This issue is a duplicate of https://github.com/Muqsit/InvMenu/issues/193. The plugin author must use InvMenu v4.4.1 to support later PocketMine releases.

**Closed as not planned** 2022-12-16 07:15 UTC
Labels: question
