### ISSUE TITLE
Crash on latest version of pocketmine and mc

### ISSUE THREAD

**Issue by Frostyyyyz** [Muqsit/InvMenu#194] opened 2022-12-04 20:14 UTC
My server crashes when i open my inventory

**Comment by Frostyyyyz** [comment] 2022-12-04 20:15
or when i use a plugin's command thats using invmenu

**Comment by Muqsit** [comment] 2022-12-04 20:37
This issue is a duplicate of #193. The plugin author must use InvMenu v4.4.1 to support later PocketMine releases.

**Closed as completed** 2022-12-06 07:23 UTC
Labels: question
