### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by HaiKHGaMer** [Muqsit/InvMenu#89] opened 2020-07-24 08:37 UTC
i do/gui and click item my server is crash here erorr message and sometimes I do/gui click item my game is Crash
![Untitled](https://user-images.githubusercontent.com/66076787/88374188-84e2e300-cdc3-11ea-8e0b-89d1cd578e7f.png)

**Comment by Muqsit** [comment] 2020-07-24 09:29
Duplicate of #88

**Closed by Muqsit** 2020-07-24 09:29 UTC
Labels: duplicate

**Comment by HaiKHGaMer** [comment] 2020-07-24 09:33
how??

**Comment by HaiKHGaMer** [comment] 2020-07-24 09:36
i dont understand

**Comment by HaiKHGaMer** [comment] 2020-07-24 09:48
Pls help me I don't understand
