### ISSUE TITLE
Client crashs when a chest is closed by a plugin

### ISSUE THREAD

**Issue by Wertzui123** [Muqsit/InvMenu#93] opened 2020-07-31 19:47 UTC
**Sourcode:**
```php
$ui = InvMenu::create(InvMenu::TYPE_CHEST);
$ui->setListener(function (Player $player, Item $clickedOn, Item $clickedWith, SlotChangeAction $action) {
    $player->removeWindow($action->getInventory());
});
$ui->send($player);
```

**Expected result:**
An inventory which closes when you move an item into it.

**Actual result:**
When you move an item into the inventory, it closes, the client starts freezing and crashes after a few seconds.

**Software and hardware information:**
PocketMine: 3.14.2
InvMenu: Latest version (downloaded using git clone)
Tested on: Windows 10, Android

**Comment by Muqsit** [comment] 2020-08-01 05:30
Duplicate of #84

**Closed by Muqsit** 2020-08-01 05:30 UTC
Labels: duplicate
