### ISSUE TITLE
How to fix this bug pls help

### ISSUE THREAD

**Issue by bittu2008** [Muqsit/InvMenu#150] opened 2021-07-21 07:06 UTC
2021-07-21 [06:27:01] [Server thread/INFO]: JayGamerz300[/223.238.198.42:49524] logged in with entity id 1 at (world, 256, 65, 256)
2021-07-21 [06:27:02] [Server thread/NOTICE]: [AutoMineReset] INFO:
The timer has beenEnabled!
2021-07-21 [06:27:16] [Server thread/CRITICAL]: Error: "Class 'Ds\Queue' not found" (EXCEPTION) in "plugins/BedwarsOPPP.phar/src/vixikhd/BedWarsSolo/libs/muqsit/invmenu/session/PlayerNetwork" at line 52
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #0 plugins/BedwarsOPPP.phar/src/vixikhd/BedWarsSolo/libs/muqsit/invmenu/session/PlayerManager(38): vixikhd\BedWarsSolo\libs\muqsit\invmenu\session\PlayerNetwork->__construct(object pocketmine\Player, object vixikhd\BedWarsSolo\libs\muqsit\invmenu\session\network\handler\ClosurePlayerNetworkHandler)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #1 plugins/BedwarsOPPP.phar/src/vixikhd/BedWarsSolo/libs/muqsit/invmenu/InvMenuEventHandler(69): vixikhd\BedWarsSolo\libs\muqsit\invmenu\session\PlayerManager::create(object pocketmine\Player)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): vixikhd\BedWarsSolo\libs\muqsit\invmenu\InvMenuEventHandler->onPlayerJoin(object pocketmine\event\player\PlayerJoinEvent)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object vixikhd\BedWarsSolo\libs\muqsit\invmenu\InvMenuEventHandler, object pocketmine\event\player\PlayerJoinEvent)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Player(1099): pocketmine\event\Event->call()
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(310): pocketmine\Player->doFirstSpawn()
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/network/mcpe/protocol/SetLocalPlayerAsInitializedPacket(45): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
2021-07-21 [06:27:16] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket)

How to fix pls tell pls

**Comment by Muqsit** [comment] 2021-07-21 09:18
This was fixed in https://github.com/Muqsit/InvMenu/commit/af247cf4b5d43b72c5a3fff74d13898bcf118cb1
If you aren't the developer of the plugin, contact them and ask them to update the InvMenu virion / library for that plugin.

Duplicate of #147

**Closed as completed by Muqsit** 2021-07-21 09:18 UTC
Labels: duplicate
