### ISSUE TITLE
Crash on inv open due to protocol changes.

### ISSUE THREAD

**Issue by J1b1x** [Muqsit/InvMenu#193] opened 2022-12-02 23:06 UTC
When you open your inventory, the server crashes since the last PocketMine-MP update removed the getWindow function.
Here's the error:
Error: "Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()" (EXCEPTION) in "muqsit/invmenu/session/network/PlayerNetwork" at line 140

**Comment by Muqsit** [comment] 2022-12-02 23:50
InvMenu is up to date with the latest stable PocketMine release. Plugins must update their InvMenu version to v4.4.1 to support later PocketMine releases (duplicate of #191).

**Closed as not planned** 2022-12-03 08:25 UTC
