### ISSUE TITLE
PS4

### ISSUE THREAD

**Issue by iTzMeFlorian** [Muqsit/InvMenu#99] opened 2020-08-27 18:15 UTC
PlayStation4 players don't get a Menu sent by InvMenu

**Comment by Muqsit** [comment] 2020-08-27 18:23
Duplicate of #73

**Closed by Muqsit** 2020-08-27 18:23 UTC
Labels: duplicate

**Comment by xxAROX** [comment] 2020-08-29 14:34
I found a method, its very unstable but it works:
PlayerNetwork.php
```php
	public function notify(int $timestamp) : void{
		if ($this->session instanceof MyCustomPlayer) {
			if ($this->session->getOS() /*returns the device-os, you can find them at 'LoginPacket::$clientData["DeviceOS"]'*/ == 11) {
				if ($this->current !== null && $timestamp !== $this->current->timestamp) {
					$this->processCurrent(true);
				}
			} else {
				if ($this->current !== null && $timestamp === $this->current->timestamp) {
					$this->processCurrent(true);
				}
			}
		}
	}
```
