### ISSUE TITLE
Ds\queue

### ISSUE THREAD

**Issue by reyyan987** [Muqsit/InvMenu#155] opened 2021-09-16 08:34 UTC
I am getting this ds\queue error in complex crate and auction house as they use inv menu and I have latest invmenu vition from poggit but I'm still having this error

**Comment by Muqsit** [comment] 2021-09-16 09:17
If you are the developer of either of those plugins, update version of InvMenu virion from .poggit.yml and push a commit so an updated poggit build is created.
(Duplicate of https://github.com/Muqsit/InvMenu/issues/147)

**Closed by Muqsit** 2021-09-16 09:17 UTC
Labels: duplicate
