### ISSUE TITLE
1.20.10 broke something

### ISSUE THREAD

**Issue by dadodasyra** [Muqsit/InvMenu#216] opened 2023-07-12 13:24 UTC
Seems like nothing is happening, the chest pops out put not the UI..

**Comment by alvin0319** [comment] 2023-07-12 16:56
```php
if(!$sender instanceof Player) return;
			$pk = UpdateBlockPacket::create(
				BlockPosition::fromVector3($pos = $sender->getPosition()->add(0, 5, 0)),
				TypeConverter::getInstance()->getBlockTranslator()->internalIdToNetworkId(VanillaBlocks::CHEST()->getStateId()),
				UpdateBlockPacket::FLAG_NETWORK,
				UpdateBlockPacket::DATA_LAYER_NORMAL
			);
			$sender->getNetworkSession()->sendDataPacket($pk);
			$sender->getNetworkSession()->sendDataPacket(
				UpdateBlockPacket::create(
					BlockPosition::fromVector3($pos->add(1, 0, 0)),
					TypeConverter::getInstance()->getBlockTranslator()->internalIdToNetworkId(VanillaBlocks::CHEST()->getStateId()),
					UpdateBlockPacket::FLAG_NETWORK,
					UpdateBlockPacket::DATA_LAYER_NORMAL
				)
			);
			$sender->getNetworkSession()->sendDataPacket(
				BlockActorDataPacket::create(
					BlockPosition::fromVector3($pos),
					new CacheableNbt(CompoundTag::create()
						->setString(Tile::TAG_ID, "Chest")
						->setInt(Tile::TAG_X, $pos->getFloorX())
						->setInt(Tile::TAG_Y, $pos->getFloorY())
						->setInt(Tile::TAG_Z, $pos->getFloorZ())
						->setString(Chest::TAG_CUSTOM_NAME, "TEST")
						->setInt(Chest::TAG_PAIRX, $pos->getFloorX() + 1)
						->setInt(Chest::TAG_PAIRZ, $pos->getFloorZ())
					)
				)
			);
			$sender->getNetworkSession()->sendDataPacket(
				BlockActorDataPacket::create(
					BlockPosition::fromVector3($pos->add(1, 0, 0)),
					new CacheableNbt(CompoundTag::create()
						->setString(Tile::TAG_ID, "Chest")
						->setInt(Tile::TAG_X, $pos->getFloorX() + 1)
						->setInt(Tile::TAG_Y, $pos->getFloorY())
						->setInt(Tile::TAG_Z, $pos->getFloorZ())
						->setString(Chest::TAG_CUSTOM_NAME, "TEST")
						->setInt(Chest::TAG_PAIRX, $pos->getFloorX())
						->setInt(Chest::TAG_PAIRZ, $pos->getFloorZ())
					)
				)
			);
			$this->getScheduler()->scheduleDelayedTask(new ClosureTask(function() use ($sender, $pos) : void{
				$sender->getNetworkSession()->sendDataPacket(
					ContainerOpenPacket::blockInv(
						1,
						WindowTypes::CONTAINER,
						BlockPosition::fromVector3($pos),
					)
				);
			}), 10);
			$sender->sendMessage("Complete");
```
From what I can tell is that this code works. Looks like we need to add a delay for container opening?

**Comment by dadodasyra** [comment] 2023-07-12 18:42
@alvin0319 Can you confirm this is not related to my code and your InvMenu is broken too ?

**Comment by dadodasyra** [comment] 2023-07-12 18:44
I don't really understand what could have break since I found no server software changing anything about UIs..

**Comment by dries-c** [comment] 2023-07-12 18:51
We're experiencing the same issue. However I've no clue what causes it yet

**Comment by supercrafter333** [comment] 2023-07-12 22:16
If I try to open a InvMenu, I can open it one time. If I try to open it a second time (no matter what contents or name the invmenu-inventory have), it doesn't work - no inventory is opening. If I try to open my own player-inventory, everything works fine.

I think the InvMenu-inventory wasn't closed the right way. Maybe we have to show what the code for closing the inventory do.

I also tried to use debug-messages but that wasn't helpful.

**Comment by aabstractt** [comment] 2023-07-13 00:25
![image](https://github.com/Muqsit/InvMenu/assets/29084446/c38ba2b7-6a36-42f1-aced-1ed50a8606ec)
The issue is the timestamp, InvMenu store the timestamp without long value and MCPE sent the packet with long (many 0)

**Comment by supercrafter333** [comment] 2023-07-13 00:27
> ![image](https://github.com/Muqsit/InvMenu/assets/29084446/c38ba2b7-6a36-42f1-aced-1ed50a8606ec)
> The issue is the timestamp, InvMenu store the timestamp with an long value and MCPE sent the packet without long

Any idea how to fix?

**Comment by aabstractt** [comment] 2023-07-13 00:31
![image](https://github.com/Muqsit/InvMenu/assets/29084446/07b8fdd3-c8ec-4bc1-ac0a-866571e057ec)

This is the quickfix on the PlayerNetwork method notify

**Closed as completed** 2023-07-13 22:40 UTC
Labels: client-sided bug

**Comment by Muqsit** [comment] 2023-07-13 22:49
Seems like there was a change in behavior of NetworkStackLatencyPacket in Bedrock Edition v1.20.10. This protocol change may be impacting PlayStation users as well, however I do not have access to one at the moment to test it.

Thank you for the details and analysis @alvin0319 @supercrafter333 @aabstractt.
